server:
  port: 8085
spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432}/${DATABASE_NAME:statistic_payment_db}
    username: ${DATABASE_USERNAME:user}
    password: ${DATABASE_PASSWORD:user}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    open-in-view: true


